spring.datasource.url=jdbc:h2:C:/Users/Alexey/webApplicationMarketPlace/databases/marketplace
#C:\Users\Alexey\Read_user_admin_students-main\testdb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= true

spring.main.allow-circular-references=true
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
upload.path=./uploads/images/

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

